(function(){
'use strict';
const C=window.CHEONGRYEOM_CONTENT;
const rooms={};
const listeners=new Map();
const mode=document.body.classList.contains('teacher-page')?'teacher':'student';
const uid=mode==='student'?'demo-student':'demo-teacher';
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
function room(code){if(!rooms[code])rooms[code]={meta:{title:'청렴ON 예비 직업인 직업윤리 자격과정'},control:{stage:'waiting',index:0,phase:'single',reveal:false,locked:false,timerEnd:null,teamPhase:'briefing'},participants:{},presence:{},answers:{written:{},practical:{},team:{role:{},mid:{},report:{}}},pledges:{}};return rooms[code];}
function parts(path){return String(path||'').split('/').filter(Boolean);}
function getAt(obj,path){let x=obj;for(const k of parts(path)){if(x==null)return null;x=x[k];}return x==null?null:x;}
function setAt(obj,path,val){const p=parts(path);let x=obj;for(let i=0;i<p.length-1;i++)x=x[p[i]]||(x[p[i]]={});if(!p.length)return; x[p[p.length-1]]=val;}
function mergeAt(obj,path,patch){const cur=getAt(obj,path)||{};setAt(obj,path,{...cur,...patch});}
function key(code,path){return code+'|'+path;}
function notify(code){for(const [k,set] of listeners){if(!k.startsWith(code+'|'))continue;const path=k.slice(code.length+1);const value=clone(getAt(room(code),path));for(const cb of [...set]){try{cb(value)}catch(e){console.error(e)}}}}
function on(path,code,cb){const k=key(code,path);if(!listeners.has(k))listeners.set(k,new Set());listeners.get(k).add(cb);queueMicrotask(()=>cb(clone(getAt(room(code),path))));return()=>listeners.get(k)?.delete(cb);}
function track(key){return window.CHEONGRYEOM_TRACK(key||'business');}
function practicalAnswer(q,variant=0){
 if(q.kind==='procurement')return {choice:variant%5===4?0:1,work:{openedDocs:q.docs.map(x=>x.id),activeDoc:q.docs[0]?.id||null,conflictVendor:'C',criteria:q.criteria.map(x=>x.key),selectedVendor:variant%5===4?0:1,disclosure:true,reason:'비용·품질·납기와 이해관계를 같은 기준으로 비교하고 이해관계는 공개하여 기록했습니다.'}};
 if(q.kind==='sequence')return {choice:0,work:{order:['fact','reissue','report','actual'],note:'누락 사실을 확인하고 다시 점검한 뒤 담당자에게 보고하여 실제 확인 결과와 조치내용을 기록합니다.'}};
 const scores={};q.candidates.forEach(c=>{scores[c.id]={};q.rubricFields.forEach(f=>scores[c.id][f.key]=Math.max(1,Number(c.reference?.[f.key]||Math.round(f.max*.8))))});return {choice:0,work:{scores:clone(scores),lockedScores:clone(scores),revealed:true,response:0,reason:'상급자의 선호나 압력과 관계없이 처음 공개된 동일한 평가기준과 자료에 따라 객관적으로 최종안을 판단하고 기록합니다.'}};
}

function practicalAnswerSupporter(q){
 if(q.kind==='procurement')return {choice:2,work:{openedDocs:q.docs.slice(0,2).map(x=>x.id),activeDoc:q.docs[0]?.id||null,conflictVendor:'C',criteria:q.criteria.slice(0,2).map(x=>x.key),selectedVendor:2,disclosure:false,reason:'비용과 품질은 비교했지만 이해관계 처리와 기록이 충분하지 않았습니다.'}};
 if(q.kind==='sequence')return {choice:0,work:{order:['fact','reissue','report','hide'],note:'누락을 확인하고 보고했지만 실제 기록까지 충분히 마무리하지 못했습니다.'}};
 const scores={};q.candidates.forEach(c=>{scores[c.id]={};q.rubricFields.forEach(f=>scores[c.id][f.key]=Math.max(1,Math.round(Number(f.max||10)*.35)))});return {choice:2,work:{scores:clone(scores),lockedScores:clone(scores),revealed:true,response:2,reason:'기준은 확인했지만 추가정보가 판단에 일부 영향을 주었습니다.'}};
}
function practicalAnswerConfirmation(q){
 if(q.kind==='procurement')return {choice:2,work:{openedDocs:[],activeDoc:null,conflictVendor:'NONE',criteria:q.criteria.slice(0,2).map(x=>x.key),selectedVendor:2,disclosure:false,reason:'가격 위주로 선택했습니다.'}};
 if(q.kind==='sequence')return {choice:0,work:{order:['mix','hide','fact','reissue'],note:'빠르게 처리하려고 했습니다.'}};
 const scores={};q.candidates.forEach(c=>{scores[c.id]={};q.rubricFields.forEach(f=>scores[c.id][f.key]=1)});return {choice:1,work:{scores:clone(scores),lockedScores:clone(scores),revealed:true,response:1,reason:'주변 의견을 따랐습니다.'}};
}
const names=['김하린','이도윤','박서준','최유진','정민재','한서윤','오지훈','임채원','윤도현','강수빈','서준혁','신예린','문지호','백소연','조현우','송예은','배민준','고하은','안태윤','류서아','남지후','권다은','차민석','노유나','황준호'];
function seedTeacher(code,title){const r=room(code);r.meta.title=title||r.meta.title;r.participants={};r.presence={};r.answers={written:{},practical:{},team:{role:{},mid:{},report:{}}};r.pledges={};r.control={stage:'waiting',index:0,phase:'single',reveal:false,locked:false,timerEnd:null,teamPhase:'briefing'};
 const supporterDemo=new Set([2,6,10,14,18]);
 const confirmationDemo=new Set([21,24]);
 C.trackList.forEach((tl,ti)=>{for(let j=0;j<5;j++){const n=ti*5+j,id='demo-'+String(n+1).padStart(2,'0'),tr=track(tl.key),isSupporter=supporterDemo.has(n),isConfirmation=confirmationDemo.has(n);r.participants[id]={studentName:names[n],schoolLevel:'high',trackKey:tl.key,trackName:tl.name,demoTier:isConfirmation?'confirmation':isSupporter?'supporter':'leader',joinedAt:Date.now()-n*1500};r.presence[id]={at:Date.now()};tr.written.forEach((q,qi)=>{let wrong=false;if(isConfirmation)wrong=true;else if(isSupporter)wrong=qi!==n%tr.written.length;else wrong=(j===4&&qi===j%tr.written.length);(r.answers.written[q.id] ||= {})[id]={choice:wrong?((q.correct+1)%q.options.length):q.correct,correct:!wrong,submittedAt:Date.now()};});tr.practical.forEach((q,qi)=>{(r.answers.practical[q.id] ||= {})[id]=isConfirmation?practicalAnswerConfirmation(q):isSupporter?practicalAnswerSupporter(q):practicalAnswer(q,(j+qi)%6);});r.pledges[id]={text:[`${tl.short} 직무에서 실제 수치와 기록을 바꾸지 않고 사실대로 보고하겠습니다.`,`친분이나 편의보다 공개된 직무기준을 먼저 확인하고 같은 기준을 적용하겠습니다.`,`문제를 발견하면 숨기지 않고 확인·보고·조치·기록까지 책임 있게 마무리하겠습니다.`,`고객과 동료에게 미치는 영향을 생각하고 안전과 공정을 함께 지키겠습니다.`,`AI와 디지털 자료를 사용할 때 출처와 사용범위를 투명하게 기록하겠습니다.`][j],savedAt:Date.now()};}});notify(code);}
function ensureStudentTeam(code,trackKey){const r=room(code),tr=track(trackKey), self=r.participants[uid];if(!self)return;const otherNames=['김하린','이도윤','박서준'];const roleKeys=['records','finance','purchase','operations'];const selfIndex=2;const members=[];for(let i=0;i<4;i++){const id=i===selfIndex?uid:'mate-'+i;const rk=roleKeys[i], role=tr.team.roles[rk];const p=i===selfIndex?self:{studentName:otherNames[i<2?i:i-1],schoolLevel:'high',trackKey,trackName:tr.name};Object.assign(p,{teamId:'demo-team',teamLabel:`${tr.short} 1팀`,teamSize:4,teamRoleKey:rk,teamRoleName:role.name,teamExtraRoleKeys:i===selfIndex?['verify']:[]});if(id!==uid)r.participants[id]=p;members.push({uid:id,studentName:p.studentName,trackKey,roleKey:rk,roleName:role.name,isRecorder:rk==='records',extraRoleKeys:p.teamExtraRoleKeys||[]});}
r.control.teamRosters={'demo-team':{teamId:'demo-team',teamLabel:`${tr.short} 1팀`,trackKey,trackName:tr.name,members}};notify(code);}
function seedStudentMateAnswers(code){const r=room(code), self=r.participants[uid];if(!self?.teamId)return;const tr=track(self.trackKey), roster=r.control.teamRosters?.[self.teamId];for(const m of roster.members){if(m.uid===uid)continue;const role=tr.team.roles[m.roleKey];r.answers.team.role[m.uid]={choice:role.correct,work:{teamId:self.teamId,roleKey:m.roleKey,riskLevel:m.roleKey==='finance'?'mid':'high',preliminaryVendor:m.roleKey==='operations'?'A':'B',note:`${role.secret} 따라서 ${role.keywords.slice(0,3).join('·')}을 확인하고 공개된 기준으로 판단해야 합니다.`,question:m.roleKey==='finance'?'구매 담당에게 품질과 정확한 납기조건을 확인하고 싶습니다.':'다른 담당자가 가진 비용·납기·이해관계 정보를 함께 확인하고 싶습니다.',extraRoleKeys:m.extraRoleKeys||[]}};}
}
function seedStudentMateMidAnswers(code){const r=room(code),self=r.participants[uid];if(!self?.teamId)return;const roster=r.control.teamRosters?.[self.teamId];if(!r.answers.team.mid)r.answers.team.mid={};for(const m of roster.members){if(m.uid===uid)continue;if(r.answers.team.mid[m.uid])continue;r.answers.team.mid[m.uid]={choice:0,work:{teamId:self.teamId,vendor:m.roleKey==='operations'?'A':'B',reason:'팀 상황판의 납기·품질·비용·이해관계 정보를 함께 비교하여 현재 시점의 판단을 정리했습니다.'}};}}
function makeBoards(code){const r=room(code), boards={};const byTeam={};Object.entries(r.participants).forEach(([id,p])=>{if(p.teamId)(byTeam[p.teamId] ||= []).push([id,p])});for(const [teamId,arr] of Object.entries(byTeam)){const first=arr[0][1],tr=track(first.trackKey), roster=r.control.teamRosters?.[teamId];boards[teamId]={teamId,teamLabel:first.teamLabel,trackKey:first.trackKey,trackName:first.trackName,updatedAt:Date.now(),members:(roster?.members||arr.map(([id,p])=>({uid:id,studentName:p.studentName,roleKey:p.teamRoleKey,roleName:p.teamRoleName,extraRoleKeys:p.teamExtraRoleKeys||[]}))).map(m=>{const a=r.answers.team.role[m.uid],w=a?.work||{},mid=r.answers.team.mid?.[m.uid],mw=mid?.work||{},role=tr.team.roles[m.roleKey], report=r.answers.team.report[m.uid];return {uid:m.uid,studentName:m.studentName,roleKey:m.roleKey,roleName:m.roleName,roleSubmitted:!!a,midSubmitted:!!mid,midVendor:mw.vendor||'',midReason:mw.reason||'',reportSubmitted:!!report,coreJudgment:a&&role?role.options?.[Number(a.choice)]||'':'',riskLevel:w.riskLevel||'',preliminaryVendor:w.preliminaryVendor||'',note:w.note||'',question:w.question||'',extraRoleNames:(m.extraRoleKeys||[]).map(k=>tr.team.roles[k]?.name).filter(Boolean)};})};}return boards;}
function seedFinalReports(code){const r=room(code);const groups={};Object.entries(r.participants).forEach(([id,p])=>{if(p.teamId)(groups[p.teamId] ||= []).push([id,p])});for(const [teamId,arr] of Object.entries(groups)){const tr=track(arr[0][1].trackKey),goodI=tr.team.issues.filter(x=>x.good).slice(0,4).map(x=>x.key),goodC=tr.team.criteria.filter(x=>x.good).slice(0,4).map(x=>x.key);for(const [id,p] of arr){if(id===uid&&mode==='student')continue;if(r.answers.team.report[id])continue;const other=arr.find(x=>x[0]!==id)?.[0]||null;r.answers.team.report[id]={choice:tr.team.vendors.findIndex(v=>v.id===tr.team.finalVendor),work:{teamId,issues:goodI,criteria:goodC,conflictResponse:0,twistResponse:0,vendor:tr.team.finalVendor,influenceUid:other,reason:`팀 상황판의 비용·품질·납기·이해관계 정보를 종합하고 돌발상황 이후에도 공개된 기준을 동일하게 적용하여 ${tr.team.finalVendor}안을 최종 선택했습니다.`}};}}
}
function scoreStudentTeam(code){const r=room(code), self=r.participants[uid];if(!self?.teamId)return;seedStudentMateAnswers(code);seedFinalReports(code);const tr=track(self.trackKey),roster=r.control.teamRosters[self.teamId],reports=roster.members.map(m=>({uid:m.uid,answer:r.answers.team.report[m.uid]})),members=roster.members.map(m=>({uid:m.uid,roleKey:m.roleKey,answer:r.answers.team.role[m.uid]})),ev=window.CHEONGRYEOM_EVALUATE_TEAM_REPORT(tr.team,reports,members);r.control.teamScores={[self.teamId]:{teamLabel:self.teamLabel,trackKey:self.trackKey,trackName:self.trackName,teamScore:ev.score,details:ev.details,impact:ev.impact,consensus:ev.consensus||{},submitted:ev.submitted||reports.filter(x=>x.answer).length,memberCount:roster.members.length,publishedAt:Date.now()}};r.control.teamBoards=makeBoards(code);}
function fillTeacherRoleAnswers(code){const r=room(code);Object.entries(r.participants).forEach(([id,p])=>{if(!p.teamId||r.answers.team.role[id])return;const tr=track(p.trackKey),role=tr.team.roles[p.teamRoleKey];r.answers.team.role[id]={choice:role.correct,work:{teamId:p.teamId,roleKey:p.teamRoleKey,riskLevel:p.teamRoleKey==='finance'?'mid':'high',preliminaryVendor:p.teamRoleKey==='operations'?'A':'B',note:`${role.secret} ${role.keywords.slice(0,4).join('·')}을 기준으로 다른 담당자의 정보와 함께 검토해야 합니다.`,question:p.teamRoleKey==='records'?'구매·운영 담당의 납기와 품질정보를 확인하고 싶습니다.':'기록 담당에게 이해관계와 공개·기록 기준을 확인하고 싶습니다.',extraRoleKeys:p.teamExtraRoleKeys||[]}};});}
async function setControl(code,patch){const r=room(code);if(mode==='teacher'&&patch?.teamPhase==='briefing'&&patch?.teamRosters){r.control={...r.control,...clone(patch)};fillTeacherRoleAnswers(code);notify(code);return;}if(mode==='teacher'&&patch?.teamPhase==='board'){fillTeacherRoleAnswers(code);patch={...patch,teamBoards:(typeof buildTeamBoards==='function'?buildTeamBoards():makeBoards(code))};}if(mode==='teacher'&&patch?.teamPhase==='checkpoint'){fillTeacherRoleAnswers(code);if(!r.answers.team.mid)r.answers.team.mid={};Object.entries(r.participants).forEach(([id,p])=>{if(!p.teamId||r.answers.team.mid[id])return;r.answers.team.mid[id]={choice:0,work:{teamId:p.teamId,vendor:p.teamRoleKey==='operations'?'A':'B',reason:'팀 상황판의 직무정보를 비교하여 돌발상황 전 현재 판단을 확정했습니다.'}};});patch={...patch,teamBoards:(typeof buildTeamBoards==='function'?buildTeamBoards():makeBoards(code))};}if(mode==='teacher'&&patch?.teamPhase==='twist'){patch={...patch,teamBoards:(typeof buildTeamBoards==='function'?buildTeamBoards():makeBoards(code))};}if(mode==='teacher'&&patch?.teamPhase==='decision'){fillTeacherRoleAnswers(code);seedFinalReports(code);patch={...patch,teamBoards:(typeof buildTeamBoards==='function'?buildTeamBoards():makeBoards(code))};}r.control={...r.control,...clone(patch)};notify(code);}
const api={configured:true,uid,init:async()=>true,on,heartbeat:async()=>true,
 createRoom:async(code,title)=>{seedTeacher(code,title);return true;},
 joinRoom:async(code,name,schoolLevel)=>{const r=room(code);r.participants[uid]={studentName:name,schoolLevel,joinedAt:Date.now()};r.presence[uid]={at:Date.now()};notify(code);return true;},
 updateMe:async(code,patch)=>{mergeAt(room(code),`participants/${uid}`,clone(patch));if(patch.trackKey)ensureStudentTeam(code,patch.trackKey);notify(code);return true;},
 submitAnswer:async(code,stage,id,payload)=>{const r=room(code);if(getAt(r,`answers/${stage}/${id}/${uid}`))throw new Error('이미 제출했습니다.');let v=clone(payload);if(stage==='written'){const tr=track(r.participants[uid]?.trackKey),q=tr.written.find(x=>x.id===id);v.correct=!!q&&Number(v.choice)===Number(q.correct);}setAt(r,`answers/${stage}/${id}/${uid}`,v);if(stage==='team'&&id==='role')seedStudentMateAnswers(code);if(stage==='team'&&id==='mid')seedStudentMateMidAnswers(code);notify(code);return true;},
 savePledge:async(code,text)=>{setAt(room(code),`pledges/${uid}`,{text,savedAt:Date.now()});notify(code);return true;},setControl,
 deleteRoom:async(code)=>{delete rooms[code];notify(code);},
 db:{ref(path){return{update:async(patch)=>{const m=String(path).match(/^rooms\/([^/]+)\/(.+)$/);if(!m)return;mergeAt(room(m[1]),m[2],clone(patch));notify(m[1]);}}}},
 demo:{room,notify,ensureStudentTeam,seedStudentMateAnswers,seedStudentMateMidAnswers,seedFinalReports,makeBoards,scoreStudentTeam,getState:code=>room(code)}
};
window.CheongDB=api;
})();