const C=CHEONGRYEOM_CONTENT,DB=CheongDB,$=s=>document.querySelector(s);let code=null,control={stage:'waiting',index:0,phase:'pre',reveal:false},participants={},presence={},answers={},pledges={};let unsubs=[];
const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)};const stages=C.stages;const stageIdx=k=>stages.findIndex(s=>s.key===k);const items=k=>k==='written'?C.written:k==='practical'?C.practical:k==='process'?C.process:[];const item=()=>items(control.stage)[Number(control.index||0)]||null;
const stageCharacter={waiting:'character-greeting.png',intro:'character-explain.png',written:'character-warning.png',practical:'character-tablet.png',process:'character-listen.png',diagnosis:'character-best.png',pledge:'character-love.png',result:'character-harmony.png'};function charBox(stage){const f=stageCharacter[stage]||'character-guide.png';return `<div class="teacher-char character-panel"><img class="official-character" src="assets/official/${f}" alt="국민권익위원회 캐릭터"></div>`;}function renderRoster(){const ids=Object.keys(participants||{}).sort((a,b)=>String(participants[a]?.studentName||'').localeCompare(String(participants[b]?.studentName||''),'ko'));$('#roster').innerHTML=ids.length?ids.map(uid=>{const p=participants[uid]||{},r=calcStudent(uid),done=r.qualification!=='과정 진행 중';return `<div class="roster-item ${done?'done':''}"><b>${p.studentName||'이름 미확인'}</b><span>${p.schoolLevel==='high'?'고등학생':'중학생'} · ${done?r.qualification:'과정 진행 중'}</span></div>`}).join(''):'<div class="empty" style="grid-column:1/-1;min-height:80px">아직 등록한 학생이 없습니다.</div>'; }
function studentURL(){const u=new URL('student.html',location.href);u.searchParams.set('room',code);return u.href}function renderNav(){$('#stageNav').innerHTML=stages.map((s,i)=>`<button class="stage-btn ${s.key===control.stage?'active':''}" data-key="${s.key}"><span>${i+1}</span>${s.name}</button>`).join('');document.querySelectorAll('.stage-btn').forEach(b=>b.onclick=()=>go(b.dataset.key,0));}
function renderQR(){const q=$('#qr');q.innerHTML='';if(window.QRCode)new QRCode(q,{text:studentURL(),width:170,height:170,colorDark:'#063b5c',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});else q.innerHTML='<div class="helper">QR 라이브러리를 불러오지 못했습니다.<br>학생 링크 복사 버튼을 사용하세요.</div>';}
function ans(stage,key){return Object.values(answers?.[stage]?.[key]||{})}function bars(labels,list){const a=Array(labels.length).fill(0);list.forEach(x=>{if(Number.isInteger(x.choice)&&a[x.choice]!=null)a[x.choice]++});const n=list.length;return labels.map((l,i)=>{const p=n?Math.round(a[i]/n*100):0;return `<div class="bar-row"><b class="bar-letter">${String.fromCharCode(65+i)}</b><div class="bar-track" title="${l}"><div class="bar-fill" style="width:${p}%"></div></div><span class="bar-value">${a[i]}명 · ${p}%</span></div>`}).join('')}
function compForUser(uid){const sums=Object.fromEntries(C.virtues.map(v=>[v.key,{s:0,n:0}]));C.written.forEach(q=>{const a=answers?.written?.[q.id]?.[uid];if(!a)return;Object.entries(q.impact||{}).forEach(([k,v])=>{sums[k].s+=(a.choice===q.correct?v:Math.round(v*.3));sums[k].n++})});C.practical.forEach(q=>{const a=answers?.practical?.[q.id]?.[uid];if(!a)return;const o=q.options[a.choice];Object.entries(o?.impact||{}).forEach(([k,v])=>{sums[k].s+=v;sums[k].n++})});return Object.fromEntries(Object.entries(sums).map(([k,v])=>[k,v.n?Math.round(v.s/v.n):0]));}
function renderClassComp(){const ids=Object.keys(participants);const vals=Object.fromEntries(C.virtues.map(v=>[v.key,0]));ids.forEach(id=>{const c=compForUser(id);C.virtues.forEach(v=>vals[v.key]+=c[v.key]||0)});$('#classComp').innerHTML=C.virtues.map(v=>{const x=ids.length?Math.round(vals[v.key]/ids.length):0;return `<div class="comp-row"><div class="comp-meta"><span>${v.name}</span><b>${x}</b></div><div class="comp-track"><span style="width:${x}%"></span></div></div>`}).join('')}
function calcStudent(uid){const S=C.scoring;let wc=0;C.written.forEach(q=>{if(answers?.written?.[q.id]?.[uid]?.choice===q.correct)wc++});const w=Math.round(wc/C.written.length*100);const ps=C.practical.map(q=>{const a=answers?.practical?.[q.id]?.[uid];return Number.isInteger(a?.choice)?q.options[a.choice]?.score:null}).filter(v=>v!=null);const p=ps.length===C.practical.length?Math.round(ps.reduce((a,b)=>a+b,0)/ps.length):0;let done=0;C.process.forEach(q=>{if(answers?.process?.[q.id+'_pre']?.[uid]&&answers?.process?.[q.id+'_post']?.[uid])done++});const pr=Math.round(done/C.process.length*100);const pl=pledges?.[uid]?.text?100:0;const total=Math.round(w*S.writtenWeight/100+p*S.practicalWeight/100+pr*S.processWeight/100+pl*S.pledgeWeight/100);const complete=ps.length===C.practical.length&&C.written.every(q=>answers?.written?.[q.id]?.[uid])&&done===C.process.length&&pl===100;const qualification=complete&&total>=S.leaderTotal&&p>=S.leaderPractical?'청렴 리더':complete?'청렴 서포터':'과정 진행 중';return {w,p,pr,pl,total,qualification};}
function renderContent(){renderNav();const st=stages.find(s=>s.key===control.stage);$('#stageKicker').textContent=st?.short||'';$('#stageTitle').textContent=st?.name||'';const q=item();let h='';$('#revealBtn').classList.toggle('hidden',control.stage!=='written');$('#revealBtn').textContent=control.reveal?'해설 숨기기':'해설 공개';
if(control.stage==='waiting')h=`<span class="eyebrow">READY</span><h2>학생 접속을 기다리고 있습니다.</h2><p class="context-box">학생이 QR 또는 4자리 참여코드로 입장하면 왼쪽의 등록·접속 인원이 실시간으로 증가합니다. 모두 입장하면 다음 단계로 진행하세요.</p>`;
if(control.stage==='intro')h=`<span class="eyebrow">ORIENTATION</span><h2>${C.intro.title}</h2><p class="context-box">${C.intro.body}</p><div class="option-grid">${C.virtues.map(v=>`<div class="option-view"><b>${v.name}</b> · ${v.tag}<br><small>${v.desc}</small></div>`).join('')}</div>`;
if(control.stage==='written')h=`<span class="eyebrow">필기 ${Number(control.index)+1}/${C.written.length}</span><h2>${q.q}</h2><div class="option-grid">${q.options.map((x,i)=>`<div class="option-view"><b>${String.fromCharCode(65+i)}.</b> ${x}</div>`).join('')}</div>${control.reveal?`<div class="feedback good"><b>정답 ${String.fromCharCode(65+q.correct)}</b><br>${q.ex}</div>`:''}`;
if(control.stage==='practical')h=`<span class="eyebrow">${q.title} · ${Number(control.index)+1}/${C.practical.length}</span><h2>${q.q}</h2><p class="context-box">${q.context}</p><div class="option-grid">${q.options.map((x,i)=>`<div class="option-view"><b>${String.fromCharCode(65+i)}.</b> ${x.text}</div>`).join('')}</div>`;
if(control.stage==='process'){const phase=control.phase||'pre';h=`<span class="eyebrow">${q.title} · ${phase==='pre'?'최초 선택':phase==='discussion'?'학급 토론':'토론 후 재선택'}</span><h2>${q.q}</h2><p class="context-box">${q.context}</p><div class="option-grid">${q.options.map((x,i)=>`<div class="option-view"><b>${String.fromCharCode(65+i)}.</b> ${x}</div>`).join('')}</div><div class="change-box"><b>토론 질문</b><br>${q.discussion.join(' · ')}</div><div class="discussion-tools"><button class="btn outline" onclick="setProcessPhase('pre')">① 최초 선택</button><button class="btn soft" onclick="setProcessPhase('discussion')">② 결과·토론</button><button class="btn primary" onclick="setProcessPhase('post')">③ 재선택</button></div>`;}
if(control.stage==='diagnosis')h=`<span class="eyebrow">DIAGNOSIS</span><h2>6대 청렴역량을 함께 확인합니다.</h2><p class="context-box">학생들의 필기·실기 선택을 바탕으로 정직·약속·배려·책임·절제·공정의 학급 평균을 확인합니다. 점수는 학생의 인격을 평가하는 값이 아니라 오늘의 판단 경향을 돌아보기 위한 교육용 피드백입니다.</p>`;
if(control.stage==='pledge')h=`<span class="eyebrow">FINAL MISSION</span><h2>학교생활에서 내가 실천할 청렴 행동 한 가지</h2><p class="context-box">학생이 자신의 언어로 구체적인 실천약속을 작성합니다. 제출 여부는 실시간으로 집계됩니다.</p>`;
if(control.stage==='result'){const rs=Object.keys(participants).map(calcStudent);const leader=rs.filter(r=>r.qualification==='청렴 리더').length,supporter=rs.filter(r=>r.qualification==='청렴 서포터').length,avg=rs.length?Math.round(rs.reduce((a,b)=>a+b.total,0)/rs.length):0;h=`<span class="eyebrow">QUALIFICATION</span><h2>청렴역량 자격판정</h2><p class="context-box">과정을 완료한 학생은 청렴 서포터 또는 청렴 리더 인증을 받습니다. 학생 화면에 개인 결과와 디지털 자격증이 표시됩니다.</p><div class="result-summary"><div class="result-tile"><b>${supporter}</b><span>청렴 서포터</span></div><div class="result-tile"><b>${leader}</b><span>청렴 리더</span></div><div class="result-tile"><b>${avg}</b><span>학급 평균</span></div></div>`;}
$('#teacherContent').innerHTML=`<div class="teacher-content-grid"><div>${h}</div>${charBox(control.stage)}</div>`;renderStats();renderClassComp();renderRoster();const a=items(control.stage);$('#prevBtn').disabled=stageIdx(control.stage)===0&&Number(control.index)===0;$('#nextBtn').textContent=control.stage==='result'?'결과 공개 중':(a.length&&Number(control.index)<a.length-1?'다음 문항 →':'다음 단계 →');}
function renderStats(){const q=item();let list=[],labels=[],extra='';if(control.stage==='written'){list=ans('written',q.id);labels=q.options}else if(control.stage==='practical'){list=ans('practical',q.id);labels=q.options.map(o=>o.text)}else if(control.stage==='process'){const phase=control.phase==='post'?'post':'pre';list=ans('process',q.id+'_'+phase);labels=q.options;const pre=answers?.process?.[q.id+'_pre']||{},post=answers?.process?.[q.id+'_post']||{};let both=0,changed=0;Object.keys(post).forEach(uid=>{if(pre[uid]){both++;if(pre[uid].choice!==post[uid].choice)changed++}});if(control.phase!=='pre'&&both)extra=`<div class="change-box">토론 후 판단을 바꾼 학생 <b>${changed}/${both}명 (${Math.round(changed/both*100)}%)</b></div>`;}else if(control.stage==='pledge'){const n=Object.keys(pledges||{}).length;$('#responseChip').textContent=`${n}명 제출`;$('#statsArea').innerHTML=`<div class="empty">현재 ${n}명이 청렴 실천약속을 제출했습니다.</div>`;return}else{$('#responseChip').textContent='집계 대기';$('#statsArea').innerHTML='<div class="empty">이 단계에서는 문항 응답을 집계하지 않습니다.</div>';return}$('#responseChip').textContent=`${list.length}명 응답`;$('#statsArea').className='';$('#statsArea').innerHTML=bars(labels,list)+extra;publishPublic(labels,list,extra);}
async function publishPublic(labels,list,extra){if(!code)return;const cnt=Array(labels.length).fill(0);list.forEach(x=>{if(Number.isInteger(x.choice)&&cnt[x.choice]!=null)cnt[x.choice]++});try{await DB.publishStats(code,{participantCount:Object.keys(presence||{}).length,stage:control.stage,index:Number(control.index||0),phase:control.phase||'pre',labels,counts:cnt,total:list.length});}catch(e){}}
async function go(stage,index=0){await DB.setControl(code,{stage,index,phase:'pre',reveal:false,locked:false});}window.setProcessPhase=phase=>DB.setControl(code,{phase});
async function next(){const a=items(control.stage),i=Number(control.index||0);if(a.length&&i<a.length-1)return DB.setControl(code,{index:i+1,reveal:false,phase:'pre'});const si=stageIdx(control.stage);if(si<stages.length-1)return go(stages[si+1].key,0)}async function prev(){const a=items(control.stage),i=Number(control.index||0);if(a.length&&i>0)return DB.setControl(code,{index:i-1,reveal:false,phase:'pre'});const si=stageIdx(control.stage);if(si>0){const prev=stages[si-1].key,pa=items(prev);return go(prev,Math.max(0,pa.length-1))}}
function subscribe(){unsubs.forEach(f=>f());unsubs=[DB.on('control',code,v=>{control=v||control;renderContent()}),DB.on('participants',code,v=>{participants=v||{};$('#joinedCount').textContent=Object.keys(participants).length;renderContent()}),DB.on('presence',code,v=>{presence=v||{};$('#activeCount').textContent=Object.keys(presence).length;publishPublic([],[], '')}),DB.on('answers',code,v=>{answers=v||{};renderContent()}),DB.on('pledges',code,v=>{pledges=v||{};renderContent()})];}
async function create(){let c=$('#roomCodeInput').value.trim()||String(Math.floor(100000+Math.random()*900000));if(!/^\d{6}$/.test(c))return toast('6자리 숫자로 입력해주세요.');try{await DB.createRoom(c,$('#roomTitleInput').value.trim());code=c;$('#roomSetup').classList.add('hidden');$('#dashboard').classList.remove('hidden');$('#roomCode').textContent=c;renderQR();subscribe();toast('수업방을 개설했습니다.')}catch(e){toast(e.message||'수업방 개설 실패')}}
function csv(){const rows=[['수험ID','학생이름','학교급','필기','실기','과정','실천','종합','자격','실천약속']];Object.entries(participants).forEach(([uid,p])=>{const r=calcStudent(uid);rows.push([uid,p.studentName,p.schoolLevel,r.w,r.p,r.pr,r.pl,r.total,r.qualification,pledges?.[uid]?.text||''])});const data='\ufeff'+rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'text/csv'}));a.download=`청렴ON_${code}_결과.csv`;a.click();URL.revokeObjectURL(a.href)}
(async()=>{if(!DB.configured){$('#configError').classList.remove('hidden');$('#serverStatus').textContent='설정 필요';$('#serverStatus').classList.add('error');return}try{await DB.init();$('#serverStatus').textContent='실시간 서버 연결';$('#serverStatus').classList.add('online');$('#roomSetup').classList.remove('hidden');$('#createRoomBtn').onclick=create;$('#nextBtn').onclick=next;$('#prevBtn').onclick=prev;$('#revealBtn').onclick=()=>DB.setControl(code,{reveal:!control.reveal});$('#copyLink').onclick=()=>navigator.clipboard.writeText(studentURL()).then(()=>toast('학생 링크를 복사했습니다.'));$('#exportBtn').onclick=csv;$('#deleteBtn').onclick=async()=>{if(confirm('수업방과 모든 응답을 삭제할까요?')){await DB.deleteRoom(code);location.reload()}}}catch(e){$('#configError').classList.remove('hidden');$('#serverStatus').textContent='연결 실패';$('#serverStatus').classList.add('error')}})();